== Socket이란?

* Network에서 정보가 전송되는 고유 식별자로 정의된다.
* Socket은 32비트 숫자로 지정되며, 짝수 socket은 수신 socket을 나타내고, 홀수 socket은 송신 socket을 나타낸다.(현재는 양방향 통신할 수 있어 구분되지 않는다.)
* 송신 또는 수신 프로세서가 위치한 host에 의해 식별된다.

{empty} + 

이전의 network 논문에서는 host 운영 체제의 제어하에 실행되는 process가 다수의 port에 접근할 수 있다고 가정했다. Port는 물리적 입력 또는 출력 디바이스이거나 host의 운영 체제에 대한 시스템 호출에서 지원되는 논리적 I/O 디바이스일 수 있다. 

{empty} + 

다시 말해 

* 운영 체제에서 스풀링되는 물리적인 장치로의 I/O
* 기본 특성이 변경되지 않았지만, 액세스가 제한되고 mapping 알고리즘(예: 디바이스 주소 매핑 또는 가상 미니 디스크에서의 실린더 이동)에 의해 변환된 물리적인 장치
* 운영 체제에서 유지 관리되는 디렉터리와 액세스 방법을 통해 파일 시스템에 액세스
* 프로세스 간 통신을 위한 절차
* Network protocol에서 정의된 기계 간 통신을 위한 절차

{empty} + 

Socket은 ARPA networkfootnote:[https://en.wikipedia.org/wiki/ARPANET [ARPANET]]를 통한 기계 간 통신을 위한 port의 식별자로 정의되었다. 

각 host에 할당된 socket은 알려진 process와 고유하게 연관되어 있어야 하거나 정의되어 있어야 한다. 

일부 socket의 이름은 일반적으로 알려져 있어야 하며 특정 protocol로 작동하는 알려진 process와 연결되어야 한다. (예: logger socket, RJE socket, file transfer socket). 

다른 socket의 이름은 일반적으로 알려지지 않을 수도 있지만, 일반적으로 알려진 socket을 통해 전송될 수도 있다. (예: Initial Connection Protocol(ICP)에서 logger socket을 통해 전송). 

어떤 경우에도 network를 통해 통신은 알려진 host에서 실행되는 프로세스와 연관된 각각의 socket 간에 이루어진다.

